{
 "title": "API dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Inbound requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_request_duration_count{job=\"Api\"}[$__interval]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "http_server_current_requests{job=\"Api\"}",
     "legendFormat": "Current requests"
    }
   ]
  },
  {
   "title": "Inbound requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_request_duration_count{job=\"Api\"}[$__rate_interval]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_bucket{job=\"Api\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_bucket{job=\"Api\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_request_duration_bucket{job=\"Api\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_bucket{job=\"Api\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5 percentile (average)"
    }
   ]
  },
  {
   "title": "Inbound requests per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(http_server_request_duration_count{job=\"Api\"}[$__interval])",
     "legendFormat": "Total requests for instance {{instance}}"
    },
    {
     "expr": "http_server_current_requests{job=\"Api\"}",
     "legendFormat": "Current requests for instance {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound requests per second per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(http_server_request_duration_count{job=\"Api\"}[$__rate_interval])",
     "legendFormat": "Requests per second for instance {{instance}}"
    }
   ]
  },
  {
   "title": "Threading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_queue_length{job=\"Api\"}",
     "legendFormat": "Thread pool queue length {{instance}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=\"Api\"}",
     "legendFormat": "Thread pool thread count {{instance}}"
    }
   ]
  },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size{job=\"Api\"}",
     "legendFormat": "{{generation}} size {{instance}}"
    }
   ]
  },
  {
   "title": "Memory - Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(generation) (process_runtime_dotnet_gc_heap_size{job=\"Api\"})",
     "legendFormat": "GC heap size {{instance}}"
    },
    {
     "expr": "process_memory_usage{job=\"Api\"}",
     "legendFormat": "Memory usage {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_time{job=\"Api\"}[$__rate_interval])",
     "legendFormat": "Cpu usage {{state}} {{instance}}"
    },
    {
     "expr": "sum without(state) (rate(process_cpu_time{job=\"Api\"}[$__rate_interval]))",
     "legendFormat": "Cpu usage {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(process_runtime_dotnet_gc_allocations_size{job=\"Api\"}[$__rate_interval])",
     "legendFormat": "Allocations per second {{instance}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "irate(process_runtime_dotnet_gc_collections_count{job=\"Api\"}[$__rate_interval])",
     "legendFormat": "GC per second {{generation}} {{instance}}"
    },
    {
     "expr": "sum without(generation) (irate(process_runtime_dotnet_gc_collections_count{job=\"Api\"}[$__rate_interval]))",
     "legendFormat": "GC per second {{instance}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_fragmentation_size{job=\"Api\"}",
     "legendFormat": "Heap fragmentation {{generation}} {{instance}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_fragmentation_size{job=\"Api\"} / process_runtime_dotnet_gc_heap_size{job=\"Api\"}",
     "legendFormat": "Heap fragmentation % {{generation}} {{instance}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Worker dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Inbound events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_event_active{job=\"Worker\"})",
     "legendFormat": "Current events"
    },
    {
     "expr": "sum(kafka_consumer_event_duration_count{job=\"Worker\"})",
     "legendFormat": "Total events"
    }
   ]
  },
  {
   "title": "Inbound events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumer_event_duration_count{job=\"Worker\"}[$__rate_interval]))",
     "legendFormat": "Events per second"
    }
   ]
  },
  {
   "title": "Event handling duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(kafka_consumer_event_duration_bucket{job=\"Worker\"}[$__rate_interval])))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_event_duration_bucket{job=\"Worker\"}[$__rate_interval])))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(kafka_consumer_event_duration_bucket{job=\"Worker\"}[$__rate_interval])))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(kafka_consumer_event_duration_bucket{job=\"Worker\"}[$__rate_interval])))",
     "legendFormat": "50 percentile (average)"
    }
   ]
  },
  {
   "title": "Inbound events per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_event_active{job=\"Worker\"}",
     "legendFormat": "Current events {{instance}}"
    },
    {
     "expr": "kafka_consumer_event_duration_count{job=\"Worker\"}",
     "legendFormat": "Total events {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound events per second per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(kafka_consumer_event_duration_count{job=\"Worker\"}[$__rate_interval])",
     "legendFormat": "Events per second {{instance}}"
    }
   ]
  },
  {
   "title": "Threading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_queue_length{job=\"Worker\"}",
     "legendFormat": "Thread pool queue length {{instance}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=\"Worker\"}",
     "legendFormat": "Thread pool thread count {{instance}}"
    }
   ]
  },
  {
   "title": "DB commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(db_client_commands_duration_count{job=\"Worker\"})",
     "legendFormat": "Total db commands"
    },
    {
     "expr": "sum(db_client_commands_executing{job=\"Worker\"})",
     "legendFormat": "Total db commands executing"
    }
   ]
  },
  {
   "title": "DB commands per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(db_client_commands_duration_count{job=\"Worker\"}[$__rate_interval])",
     "legendFormat": "Commands per second {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_time{job=\"Worker\"}[$__rate_interval])",
     "legendFormat": "Cpu usage {{state}} {{instance}}"
    },
    {
     "expr": "sum without(state) (rate(process_cpu_time{job=\"Worker\"}[$__rate_interval]))",
     "legendFormat": "Cpu usage {{instance}}"
    }
   ]
  },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size{job=\"Worker\"}",
     "legendFormat": "{{generation}} size {{instance}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "irate(process_runtime_dotnet_gc_collections_count{job=\"Worker\"}[$__rate_interval])",
     "legendFormat": "GC per second {{generation}} {{instance}}"
    },
    {
     "expr": "sum without(generation) (irate(process_runtime_dotnet_gc_collections_count{job=\"Worker\"}[$__rate_interval]))",
     "legendFormat": "GC per second {{instance}}"
    }
   ]
  },
  {
   "title": "Memory - Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(generation) (process_runtime_dotnet_gc_heap_size{job=\"Worker\"})",
     "legendFormat": "GC heap size {{instance}}"
    },
    {
     "expr": "process_memory_usage{job=\"Worker\"}",
     "legendFormat": "Memory usage {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(process_runtime_dotnet_gc_allocations_size{job=\"Worker\"}[$__rate_interval])",
     "legendFormat": "Allocations per second {{instance}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_fragmentation_size{job=\"Worker\"}",
     "legendFormat": "Heap fragmentation {{generation}} {{instance}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_fragmentation_size{job=\"Worker\"} / process_runtime_dotnet_gc_heap_size{job=\"Worker\"}",
     "legendFormat": "Heap fragmentation % {{generation}} {{instance}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  }
 ]
}