apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  local-config.yaml: |
    # https://grafana.com/docs/loki/latest/configuration/examples/#complete-local-configyaml
    # https://github.com/grafana/loki/blob/6a7403c4f5cd0a01dea13954fe6f51631f485ad1/examples/getting-started/loki-config.yaml
    # https://github.com/grafana/loki/issues/2018#issuecomment-970789233
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        # address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      wal:
        enabled: true
        dir: /loki/wal
        
    schema_config:
      configs:
      - from: 2020-05-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

    storage_config:
      boltdb:
        directory: /tmp/loki/index

      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: loki
  name: loki
spec:
  containers:
    - image: grafana/loki:latest
      name: loki
      args: ["-config.file=/etc/loki/local-config.yaml"]
      ports:
        - containerPort: 3100
      volumeMounts:
        - name: loki-config-volume
          mountPath: /etc/loki/
  volumes:
    - name: loki-config-volume
      configMap:
        name: loki-config
---
apiVersion: v1
kind: Service
metadata:
  name: loki-svc
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100