apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    # https://github.com/grafana/tempo/blob/0c1eb275f028424fd7285742e36a9e954c52a963/example/docker-compose/shared/tempo.yaml
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:

    ingester:
      max_block_duration: 5m # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

    compactor:
      compaction:
        block_retention: 1h # overall Tempo trace retention. set for demo purposes

    storage:
      trace:
        backend: local # backend configuration to use
        wal:
          path: /tmp/tempo/wal # where to store the the wal locally
        local:
          path: /tmp/tempo/blocks

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  containers:
    - image: grafana/tempo:latest
      name: tempo
      args: ["-config.file=/etc/tempo/tempo.yaml"]
      ports:
        - name: tempo
          containerPort: 3200
        - name: otlp-grpc
          containerPort: 4317
          
      volumeMounts:
        - name: tempo-config-volume
          mountPath: /etc/tempo
  volumes:
    - name: tempo-config-volume
      configMap:
        name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-svc
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      name: tempo
      port: 3200
    - protocol: TCP
      name: otlp-grpc
      port: 4317